search_engine:  google # Possible values [google, duckduckgo]
browser:        firefox # only needed for search_engine = duckduckgo. Possible values: [firefox, chrome]
key:            # your Google API key here
searchengineid: # your search engine id here
geolocation:    # country of your google host here eg. nl. Default: ''
language:       en # restricts the search to documents in particular language eg. nl. Default: ''
